name: Continuous Integration

on: 
  pull_request: 

jobs:
  continuous_integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies, build, and test
        run: |
          npm install
          npm run build
          npm run test
