name: Continuos Itegration

on: pull_request 

jobs:
   Continuos Itegration: 
     runs-on ubuntu-latest

     steps:
       - uses: actions/checkout@v3
       - name: Using Node.js
         uses: actions/setup-node@v2
         with:
            node-version: 18.
        - name: rum install, build and test
          run : |
            npm install
            npm rum buld
            npm rum test

             